# 日志
logging:
  config: classpath:log4j.xml

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/kayn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

# 端口
server:
  port: 8888


# 淘宝客Api接口配置
taobaoke:
  url: "https://api.taobaokeapi.com"
  usertoken: "0c0d1cc55a4226364c0a914a5a04223d"
  site_id: "2255900096"
  adzone_id: "111236250012"
